[project]
name = "find-sp2x-patches"
version = "0.1.0"
description = "Find patches for spice2x compatible games using signature matching."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pefile>=2024.8.26",
]
